### ISSUE TITLE
prerender-spa-plugin error when building 170+ pages

### ISSUE THREAD

**Issue by sevfurneaux** [dillonkearns/elm-pages#137] opened 2020-08-11 20:08 UTC
I get the following error when running `yarn build` on a 170+ page elm-pages-starter site:

`ERROR in [prerender-spa-plugin] Unable to prerender all routes!`

Also when testing on Netlify, I get the same error at 140+ pages.

Looking up this error, this appears to be [timeout related](https://github.com/chrisvfritz/prerender-spa-plugin/issues/242#issuecomment-669722893). Unsure how to resolve this though 🤔

**Comment by sevfurneaux** [comment] 2020-08-27 17:30
Following a [further discussion on Slack](https://elmlang.slack.com/archives/CNSNETV37/p1598392740038300), the conclusion is it would be more performant to actually output HTML for each route via Elm with a port.

A similar approach is taken with the forked version of [elm-static-html-lib](https://github.com/eeue56/elm-static-html-lib), where firstly the compiled Elm JS is changed (`REPLACE_ME_WITH_JSON_STRINGIFY`) and then the HTML is output via a port:

https://github.com/dawehner/elm-static-html-lib/blob/d76c0bc08d397355567e0fb0ca7fabf162d44af7/templates.ts#L145

https://github.com/dawehner/elm-static-html-lib/blob/d76c0bc08d397355567e0fb0ca7fabf162d44af7/index.ts#L46-L60

**Comment by matheus23** [comment] 2020-08-31 19:39
Again, following a [discussion on slack](https://elmlang.slack.com/archives/CNSNETV37/p1598891644004600), I have some issue with the way elm-pages renders the content at the moment:

I can't render to a file path that I choose. The issue in my case was specifically `/ipfs-404.html`. Creating a `ipfs-404.md` will render to a file at `/ipfs-404/index.html`. But ipfs gateways will only look for files with the name `ipfs-404.html`.

The workaround for this issue is just moving the generated file after building. There don't seem to be issues with `content.json` when I do that.

**Comment by dillonkearns** [comment] 2020-10-27 16:26
Good news on this front, we've now confirmed that we can build 5,000 routes and beyond using the new beta build. Instructions for setting it up are here: https://github.com/dillonkearns/elm-pages/blob/master/docs/7.0.0-elm-package-upgrade-guide.md#2---beta-build-command.

@matheus23, regarding the file paths, maybe we can revisit some prior art about `route-name/index.html` vs. `route-name.html` and how other frameworks? Since there's a workaround, and the main issue in this thread has been resolved, I'll close this issue. If you think it's worth revisiting, then let's open another GitHub issue and do a little research about prior art and considerations for that convention 👍

**Closed by dillonkearns** 2020-10-27 16:26 UTC
